### ISSUE TITLE
OfflineReport tries to access root directory

### ISSUE THREAD

**Issue by sschaef** [scalameter/scalameter#98] opened 2015-04-14 13:14 UTC
Running the following test in scalameter 0.6
```scala
object Test extends PerformanceTest.OfflineReport {

  val sizes = Gen.range("size")(10, 100, 10)

  performance of "Test1" in {
    measure method "M1" in {
      using(sizes) in {
        r ⇒ (1 to r).toList
      }
    }
  }
}
```
with the sbt command
```
sbt project/test:runMain benchmark.Test
```

results in
```
Pushing to history with info: Map()
New history info: Map(time-indices -> ArrayBuffer(1))
[error] (run-main-0) java.io.FileNotFoundException: /Test1.M1.Test-0.dat (Permission denied)
java.io.FileNotFoundException: /Test1.M1.Test-0.dat (Permission denied)
	at java.io.FileOutputStream.open(Native Method)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:221)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:171)
	at org.scalameter.persistence.SerializationPersistor.saveHistory(SerializationPersistor.scala:40)
	at org.scalameter.persistence.SerializationPersistor.save(SerializationPersistor.scala:60)
	at org.scalameter.reporting.RegressionReporter$$anonfun$6$$anonfun$7.apply(RegressionReporter.scala:51)
	at org.scalameter.reporting.RegressionReporter$$anonfun$6$$anonfun$7.apply(RegressionReporter.scala:44)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:245)
	at scala.collection.immutable.List.map(List.scala:285)
	at org.scalameter.reporting.RegressionReporter$$anonfun$6.apply(RegressionReporter.scala:44)
	at org.scalameter.reporting.RegressionReporter$$anonfun$6.apply(RegressionReporter.scala:39)
	at scala.collection.TraversableLike$WithFilter$$anonfun$map$2.apply(TraversableLike.scala:728)
	at org.scalameter.utils.Tree$$anon$1.org$scalameter$utils$Tree$$anon$$recurse(Tree.scala:30)
	at org.scalameter.utils.Tree$$anon$1$$anonfun$org$scalameter$utils$Tree$$anon$$recurse$1.apply(Tree.scala:31)
	at org.scalameter.utils.Tree$$anon$1$$anonfun$org$scalameter$utils$Tree$$anon$$recurse$1.apply(Tree.scala:31)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at org.scalameter.utils.Tree$$anon$1.org$scalameter$utils$Tree$$anon$$recurse(Tree.scala:31)
	at org.scalameter.utils.Tree$$anon$1$$anonfun$org$scalameter$utils$Tree$$anon$$recurse$1.apply(Tree.scala:31)
	at org.scalameter.utils.Tree$$anon$1$$anonfun$org$scalameter$utils$Tree$$anon$$recurse$1.apply(Tree.scala:31)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at org.scalameter.utils.Tree$$anon$1.org$scalameter$utils$Tree$$anon$$recurse(Tree.scala:31)
	at org.scalameter.utils.Tree$$anon$1.foreach(Tree.scala:34)
	at scala.collection.TraversableLike$WithFilter.map(TraversableLike.scala:727)
	at org.scalameter.reporting.RegressionReporter.report(RegressionReporter.scala:39)
	at org.scalameter.Reporter$Composite$$anonfun$1.apply(Reporter.scala:25)
	at org.scalameter.Reporter$Composite$$anonfun$1.apply(Reporter.scala:25)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:35)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:245)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at org.scalameter.Reporter$Composite.report(Reporter.scala:25)
	at org.scalameter.PerformanceTest$Initialization$class.executeTests(PerformanceTest.scala:48)
	at org.scalameter.PerformanceTest.executeTests(PerformanceTest.scala:10)
	at org.scalameter.PerformanceTest$$anonfun$1.apply$mcZ$sp(PerformanceTest.scala:15)
	at org.scalameter.PerformanceTest$$anonfun$1.apply(PerformanceTest.scala:15)
	at org.scalameter.PerformanceTest$$anonfun$1.apply(PerformanceTest.scala:15)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
	at org.scalameter.PerformanceTest.main(PerformanceTest.scala:14)
	at benchmark.Test.main(Test.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
```

**Comment by jjuraszek** [comment] 2015-04-27 07:28
is there any workaround for that?

**Comment by axel22** [comment] 2015-04-28 20:16
Odd, had not noticed this before.
There should be several ways to overcome this, off the top of my head:

1. Use a custom `SerializationPersistor` with your own output root path:

    override def persistor = new SerializationPersistor("<desiredPath>/")

2. Override the `reportDir` flag when you run the task:

    $ sbt project/test:runMain <main-class> -- -CreportDir <path>

3. Use the `testOnly` task in sbt:

    > testOnly <test-class-name> -- -CreportDir <path>

**Comment by kjanosz** [comment] 2015-05-27 16:55
This is caused by lack of default context when running benchmarks using main. ScalaMeterFramework  is unaffected, so I think the easiest workaround would be:
```> testOnly <test-class-name>```
It is already fixed in [master](https://github.com/scalameter/scalameter/commit/a29adc4be46ea115c433ef840df4cfeb3931a7a2). See also #86.
@axel22 looks like this commit can be cherry picked to version/0.6 without any problem - I've just done it locally and run test and everything seems to be OK.

**Comment by axel22** [comment] 2015-05-30 16:32
Cool!
I would just release it along with the next major version (0.7) instead.

Btw, after a recent change, the default benchmark directory should be `target/benchmarks`.

**Comment by kjanosz** [comment] 2015-05-31 11:06
> Btw, after a recent change, the default benchmark directory should be target/benchmarks.

It wasn't, because of some config key assignment. See #102.

**Closed** 2015-06-17 18:35 UTC
